services:
  pillsremindertgbot:
    image: fedosovdn/pillsremindertgbot:1.0.0
    container_name: pillsremindertgbot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8090:8080"